services:
  apsoo_postgres:
    image: postgres:15
    ports:
      - 5432:5432
    container_name: apsoo_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - apsoo_net
    volumes:
      - apsoo_db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

networks:
  apsoo_net:
    driver: "bridge"

volumes:
  apsoo_db_data:
